[build]
# Set the default target for embedded builds (e.g., Cortex-M4/M7)
# Uncomment the line below to use embedded target by default
# target = "thumbv7em-none-eabihf"

[target.thumbv7em-none-eabihf]
# Example of setting a runner for flashing and debugging with probe-rs
# runner = "probe-rs run --chip STM32F401RE"