[build]
# Set the default target for embedded builds (e.g., Cortex-M4/M7)
# This prevents having to pass --target for every `cargo build`
target = "thumbv7em-none-eabihf"

[target.thumbv7em-none-eabihf]
# Example of setting a runner for flashing and debugging with probe-rs
# runner = "probe-rs run --chip STM32F401RE"